// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiwmCbzr6oA9c-q2eTC2NHoUhc7ZdNfWI',
    appId: '1:524169457574:web:696ab3ce442255a31aa967',
    messagingSenderId: '524169457574',
    projectId: 'quizlet-221b1',
    authDomain: 'quizlet-221b1.firebaseapp.com',
    storageBucket: 'quizlet-221b1.firebasestorage.app',
    measurementId: 'G-EPRX9E3S75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWi8iFli34AL74K_gbvAoa_s1pMHZGDOY',
    appId: '1:524169457574:android:9f261649154077191aa967',
    messagingSenderId: '524169457574',
    projectId: 'quizlet-221b1',
    storageBucket: 'quizlet-221b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrHR-K-URoGhtM8-PBeXDi3Tsly-bB9iE',
    appId: '1:524169457574:ios:dfcaa71f99fa6f5c1aa967',
    messagingSenderId: '524169457574',
    projectId: 'quizlet-221b1',
    storageBucket: 'quizlet-221b1.firebasestorage.app',
    iosBundleId: 'com.git.quizlet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrHR-K-URoGhtM8-PBeXDi3Tsly-bB9iE',
    appId: '1:524169457574:ios:dfcaa71f99fa6f5c1aa967',
    messagingSenderId: '524169457574',
    projectId: 'quizlet-221b1',
    storageBucket: 'quizlet-221b1.firebasestorage.app',
    iosBundleId: 'com.git.quizlet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiwmCbzr6oA9c-q2eTC2NHoUhc7ZdNfWI',
    appId: '1:524169457574:web:49f263fe3605ba0f1aa967',
    messagingSenderId: '524169457574',
    projectId: 'quizlet-221b1',
    authDomain: 'quizlet-221b1.firebaseapp.com',
    storageBucket: 'quizlet-221b1.firebasestorage.app',
    measurementId: 'G-1KMTVL7Y0R',
  );
}
